### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fipoucat** [nstauffer/topo.ridges#1] opened 2023-06-02 17:28 UTC
I an trying to install the package on ubuntu but get an error:

Error: package or namespace load failed for ‘topo.ridges’ in namespaceExport(ns, exports):
 undefined exports: elev.anim.df, elev.density.df, topo.ridges, topo.ridges.plot
Error: loading failed
Execution halted
ERROR: loading failed

Any hint on solving this?

**Comment by nstauffer** [comment] 2023-06-02 18:01
Thanks for letting me know, @fipoucat!

Looks like the deprecated/unmaintained functions were still being exported to the namespace, but they aren't now and it looks like it installs correctly for me. Doesn't mean it solved the problem for you though! Just let me know if it installs and I'll close this issue once we've confirmed.

**Comment by fipoucat** [comment] 2023-06-03 08:01
OK, installed now.

Thank you

**Closed as completed** 2023-06-03 13:14 UTC
Labels: bug
